### ISSUE TITLE
[Feature] Mouse click on a Common Point to display all diagram usages

### ISSUE THREAD

**Issue by kelly-luo** [arnab-sen/GALADE#19]
#### Current behaviour:
Currently Common Points are represented with a DataFlowConnector node, therefore it acts like how any mouse click on a node would work - by highlighting the node.

#### Desired behaviour:
Upon mouse click on a Common Point, it could possibly show a pop up to show all the references of this current Common Bus in the other diagrams. This will give users more comprehensive knowledge about the context and usage of the Common Buses.

**Comment by arnab-sen** [comment]
Added in v1.9.0. Select a node, then use the "Open Selected Node's Diagram..." option in the global context menu to jump to that node in the selected diagram
