### ISSUE TITLE
[Feature] 'More information about the node' button to be highlighted when it has a note written within

### ISSUE THREAD

**Issue by kelly-luo** [arnab-sen/GALADE#21]
#### Current behaviour:
![MoreInformationButtonHighlight](https://user-images.githubusercontent.com/62581430/104514411-1554fe80-5656-11eb-9549-1cf3cdaf1456.PNG)
Whether or not there is a note written within 'More information about the node' ? button, it will be uncoloured.
Only when you click on it, will you know if there is something written inside the note.

#### Expected behaviour:
When there are text written within the 'More information about the node' ? button, it will be highlighted a colour to indicate that there are notes inside to be read.

**Comment by arnab-sen** [comment]
Added in v1.9.0:
![image](https://user-images.githubusercontent.com/15961449/104711909-d2df0f00-5786-11eb-9bbb-81a4ffeff675.png)
![image](https://user-images.githubusercontent.com/15961449/104711933-da061d00-5786-11eb-93a0-74097cded1b3.png)
