### ISSUE TITLE
[Bug] Reference DataFlowConnectors on diagram generation to be wired into their proper ports

### ISSUE THREAD

**Issue by kelly-luo** [arnab-sen/GALADE#22]
#### Current behaviour:
Information is lost with what data type the DataFlowConnector is and therefore upon diagram generation. For the screenshot example below, the usbDeviceConnected is a DataFlowConnector<**bool**> but it will display as input into the RowButton's inputIUI port which can be confusing when reading the diagram without the code.

_Note:_ it will still build and function perfectly fine as it is just:
**usbDeviceConnected.WireTo(favouriteSetupRowButton, "fanoutList");**

![DFCLosingInformation](https://user-images.githubusercontent.com/62581430/104861663-a9480280-5995-11eb-815c-d43ff21dfd42.png)
 

#### Expected behaviour:
Upon diagram generation, DataFlowConnector<**bool**> usbDeviceConnected should be wired into favouriteSetupRowButton's input visible port which is of type IDataFlow<bool> as the screenshot below shows.

![DFCLosingInformation](https://user-images.githubusercontent.com/62581430/104862060-0bedce00-5997-11eb-9644-faedd7b9ff7f.png)

#### Steps to reproduce:
* Open any diagram with a reference abstraction that has a data type that is input into another abstraction. (_Note_: the following screenshots were gathered from MainDiagram from DataLink_ALA on 18-01-2021)

**Comment by arnab-sen** [comment]
Fixed in v1.9.0.
