### ISSUE TITLE
[Bug] Zooming out while entering abstraction class causes the overlay to stay present

### ISSUE THREAD

**Issue by davidcole1340** [arnab-sen/GALADE#23]
#### Current behavior:

After creating a new node, if you zoom out and enter the abstraction type, the "NewNode" overlay stays present after zooming back in.

#### Expected behaviour:

The overlay is not present after zooming back in and says the new abstraction type.

#### Steps to reproduce:

1. Create a new node
2. Zoom out until the overlays appear with your cursor still on the abstraction type text box
3. Enter an abstraction type and press enter
4. Zoom back in

![](https://i.gyazo.com/de06fcbd935efac2cf0b88799fd735ff.gif)

**Comment by arnab-sen** [comment]
Fixed in v1.9.0.

**Comment by arnab-sen** [comment]
Fixed in v1.9.0.
