### ISSUE TITLE
[Bug?] GALADE only recognises CRLF, not LF

### ISSUE THREAD

**Issue by davidcole1340** [arnab-sen/GALADE#24]
**Current behaviour:**

When loading a file with unix LF endings, GALADE fails to load the diagram and crashes with an exception:

![image](https://user-images.githubusercontent.com/991872/106250178-2c136c00-6278-11eb-8966-342756bf8da1.png)

Under further inspection, GALADE only splits the contents of the file based on the current environment's new line operator (CRLF on Windows)

![image](https://user-images.githubusercontent.com/991872/106250161-23bb3100-6278-11eb-84c1-2d797323de9b.png)

**Expected behaviour:**

Diagram to load correctly with CRLF and LF line endings.

**Steps to reproduce:**

Convert a file to LF line endings, open the file in GALADE.

**Possible solution:**

Splitting the contents of the code string with both CRLF and LF seem to fix the problem, however, I have not investigated further. I have tested opening files with CRLF and LF endings and it seems to be able to parse both correctly.

Line 90 of `ExtractALACode.cs`:
```csharp
var codeLines = code.Split(new []{ Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries);
```

vs

```csharp
var codeLines = code.Split(new []{ "\r\n", "\n" }, StringSplitOptions.RemoveEmptyEntries);
```

There also seems to be an issue with reading the port metadata:

![image](https://user-images.githubusercontent.com/991872/106253677-a940e000-627c-11eb-8bf6-dfdf78fb790c.png)

Saving the diagram does not work, however, putting the instantiations and wiring at the end of the file:

![image](https://user-images.githubusercontent.com/991872/106253570-87dff400-627c-11eb-8dc4-68e4fba268a8.png)

**Comment by arnab-sen** [comment]
Should be resolved by changing local text editor settings to use CLRF.
