### ISSUE TITLE
[Bug] UNDEFINED instances when using 'StoryAbstractions' folder

### ISSUE THREAD

**Issue by kelly-luo** [arnab-sen/GALADE#28]
#### Current behaviour:
When we have a folder layer called "StoryAbstractions" with re-usable instances e.g. DeviceCommunicationProgressWindow: a pre-wired pop-window, GALADE will not recognise it and set it as UNDEFINED.

#### Expected behaviour:
It will recognise on GALADE any instances within the 'StoryAbstractions' folder

#### Steps to reproduce:
Go to DataLink_ALA project's commit - 885b0f72 (Updated Application.cs summary) and try to open XRS2_Favourites diagram and the DeviceCommunicationProgressWindow instance will be undefined due to it being located in the 'StoryAbstractions' folder

**Comment by arnab-sen** [comment]
Following the reproduction steps doesn't lead to any issues, so this might be due to something else. Will close for now.
